server:
    port: 5000
    error:
        include-binding-errors: always
        include-message: always

springfox:
    documentation:
        swagger-ui:
            base-url: /documentation

spring:
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher

    application:
        name: weeding-playlist
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://wedding-db.chypldsbom4k.eu-north-1.rds.amazonaws.com:3306/wedding
        username: arvebratt
        password: Netlight2022
    jpa:
        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
        show-sql: true